controllers:
    resource: ../src/Controller/
    type: attribute
home:
    path: /{name}
    controller: App\Controller\HomeController::home
create:
    path: /article/new
    controller: App\Controller\BlogController::add